[package]
name = "leets"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
criterion = "0.5.1"
rand = "0.8.5"
plotters = {version="0.3.4"}
gnuplot = "0.0.38"
